#!/bin/bash

__envdefault_known=' '
while read -r -d '' line ; do
	key="${line%%=*}"
	__envdefault_known="$__envdefault_known $key "
done < <(env -0)

while read -r -d '' line ; do
	key="${line%%=*}"
	[ -z "${__envdefault_known##* $key *}" ] && continue
	val="${line#*=}"
	echo export "$key='$val'"
	export $key="$val"
done < <(source ${1:-/dev/stdin} >/dev/null 2>&1; env -0)
